"""simplified schema for raw telemetry data

Revision ID: 64ccb0e1ade2
Revises: dd1bec36709f
Create Date: 2026-01-09 09:58:11.043978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64ccb0e1ade2'
down_revision = 'dd1bec36709f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new telemetry tables
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_service_name'), 'events', ['service_name'], unique=False)
    op.create_index('ix_events_service_timestamp', 'events', ['service_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index('ix_events_type', 'events', ['type'], unique=False)
    
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_service_name'), 'logs', ['service_name'], unique=False)
    op.create_index('ix_logs_service_timestamp', 'logs', ['service_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_logs_trace_id'), 'logs', ['trace_id'], unique=False)
    
    # Drop all dependent tables first (those with foreign keys to incidents)
    op.execute('DROP TABLE IF EXISTS incident_alerts CASCADE')
    op.execute('DROP TABLE IF EXISTS incident_events CASCADE')
    op.execute('DROP TABLE IF EXISTS incident_services CASCADE')
    op.execute('DROP TABLE IF EXISTS incident_feedback CASCADE')
    op.execute('DROP TABLE IF EXISTS incident_logs CASCADE')
    op.execute('DROP TABLE IF EXISTS incident_timeline CASCADE')
    op.execute('DROP TABLE IF EXISTS root_cause_hypotheses CASCADE')
    op.execute('DROP TABLE IF EXISTS rca_evidence CASCADE')
    op.execute('DROP TABLE IF EXISTS rca_timeline_events CASCADE')
    op.execute('DROP TABLE IF EXISTS rca_reasons CASCADE')
    
    # Now drop incidents and other tables
    op.execute('DROP TABLE IF EXISTS incidents CASCADE')
    op.execute('DROP TABLE IF EXISTS alerts CASCADE')
    op.execute('DROP TABLE IF EXISTS alert_rules CASCADE')
    op.execute('DROP TABLE IF EXISTS alert_rule_notifications CASCADE')
    op.execute('DROP TABLE IF EXISTS suppression_policies CASCADE')
    op.execute('DROP TABLE IF EXISTS service_dependencies CASCADE')
    op.execute('DROP TABLE IF EXISTS ai_models CASCADE')
    op.execute('DROP TABLE IF EXISTS service_metric_snapshots CASCADE')
    op.execute('DROP TABLE IF EXISTS change_events CASCADE')
    op.execute('DROP TABLE IF EXISTS team_invites CASCADE')
    op.execute('DROP TABLE IF EXISTS notification_channels CASCADE')
    op.execute('DROP TABLE IF EXISTS deployment_events CASCADE')
    op.execute('DROP TABLE IF EXISTS integrations CASCADE')
    op.execute('DROP TABLE IF EXISTS analytics_snapshots CASCADE')
    
    # Update metrics table
    op.drop_constraint('metrics_service_id_fkey', 'metrics', type_='foreignkey')
    op.drop_index(op.f('ix_metrics_service_id'), table_name='metrics')
    op.drop_column('metrics', 'service_id')
    op.add_column('metrics', sa.Column('service_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index('ix_metrics_metric_name', 'metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metrics_service_name'), 'metrics', ['service_name'], unique=False)
    op.create_index('ix_metrics_service_timestamp', 'metrics', ['service_name', 'timestamp'], unique=False)
    
    # Update traces table
    op.drop_constraint('traces_service_id_fkey', 'traces', type_='foreignkey')
    op.drop_index(op.f('ix_traces_service_id'), table_name='traces')
    op.drop_column('traces', 'service_id')
    op.add_column('traces', sa.Column('service_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_traces_id'), 'traces', ['id'], unique=False)
    op.create_index(op.f('ix_traces_service_name'), 'traces', ['service_name'], unique=False)
    op.create_index('ix_traces_service_timestamp', 'traces', ['service_name', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'SRE', 'DEVELOPER', 'VIEWER', name='userroleenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('traces', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('traces', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('traces_service_id_fkey'), 'traces', 'services', ['service_id'], ['id'])
    op.drop_index('ix_traces_service_timestamp', table_name='traces')
    op.drop_index(op.f('ix_traces_service_name'), table_name='traces')
    op.drop_index(op.f('ix_traces_id'), table_name='traces')
    op.create_index(op.f('ix_traces_service_id'), 'traces', ['service_id'], unique=False)
    op.drop_column('traces', 'service_name')
    op.alter_column('services', 'health_status',
               existing_type=sa.Enum('HEALTHY', 'DEGRADED', 'CRITICAL', 'UNKNOWN', name='servicehealthenum', native_enum=False),
               type_=postgresql.ENUM('healthy', 'degraded', 'critical', 'unknown', name='servicehealthenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'::servicehealthenum"))
    op.alter_column('services', 'tier',
               existing_type=sa.Enum('CRITICAL', 'NON_CRITICAL', name='tierenum', native_enum=False),
               type_=postgresql.ENUM('critical', 'non_critical', name='tierenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'non_critical'::tierenum"))
    op.add_column('metrics', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('metrics_service_id_fkey'), 'metrics', 'services', ['service_id'], ['id'])
    op.drop_index('ix_metrics_service_timestamp', table_name='metrics')
    op.drop_index(op.f('ix_metrics_service_name'), table_name='metrics')
    op.drop_index('ix_metrics_metric_name', table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.create_index(op.f('ix_metrics_service_id'), 'metrics', ['service_id'], unique=False)
    op.drop_column('metrics', 'service_name')
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('mttr_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mttd_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('noise_reduction_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_budget_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_alerts_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correlated_groups_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('incidents_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p0_incidents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p1_incidents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p2_incidents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p3_incidents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p4_incidents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('analytics_snapshots_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_snapshots_pkey'))
    )
    op.create_index(op.f('ix_analytics_snapshots_id'), 'analytics_snapshots', ['id'], unique=False)
    op.create_table('incident_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hypothesis_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_type', postgresql.ENUM('CORRECT', 'INCORRECT', 'PARTIAL', name='feedbacktype'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['root_cause_hypotheses.id'], name=op.f('incident_feedback_hypothesis_id_fkey')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incident_feedback_incident_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('incident_feedback_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_feedback_pkey'))
    )
    op.create_index(op.f('ix_incident_feedback_id'), 'incident_feedback', ['id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('PROMETHEUS', 'OPENTELEMETRY', 'DATADOG', 'GITHUB', 'SLACK', 'ELASTICSEARCH', 'PAGERDUTY', name='integrationtypeenum'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('CONNECTED', 'DISCONNECTED', 'SYNCED', 'ERROR', name='integrationstatusenum'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('integrations_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('integrations_pkey'))
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_table('deployment_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('environment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('deployed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commit_sha', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repository', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deployment_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deployment_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rollback_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('deployment_events_organization_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('deployment_events_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deployment_events_pkey'))
    )
    op.create_index(op.f('ix_deployment_events_id'), 'deployment_events', ['id'], unique=False)
    op.create_table('rca_reasons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hypothesis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('highlighted_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['root_cause_hypotheses.id'], name=op.f('rca_reasons_hypothesis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rca_reasons_pkey'))
    )
    op.create_index(op.f('ix_rca_reasons_id'), 'rca_reasons', ['id'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('ALERT_TRIGGERED', 'ANOMALY_DETECTED', 'CHANGE_DETECTED', 'HYPOTHESIS_GENERATED', 'HUMAN_OVERRIDE', name='eventtype'), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incident_events_incident_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_events_pkey'))
    )
    op.create_index(op.f('ix_incident_events_id'), 'incident_events', ['id'], unique=False)
    op.create_table('incident_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('level', postgresql.ENUM('ERROR', 'WARN', 'INFO', 'DEBUG', name='loglevelenum'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('log_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incident_logs_incident_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('incident_logs_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_logs_pkey'))
    )
    op.create_index(op.f('ix_incident_logs_id'), 'incident_logs', ['id'], unique=False)
    op.create_table('alert_rule_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name=op.f('alert_rule_notifications_alert_rule_id_fkey')),
    sa.ForeignKeyConstraint(['notification_channel_id'], ['notification_channels.id'], name=op.f('alert_rule_notifications_notification_channel_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_rule_notifications_pkey'))
    )
    op.create_index(op.f('ix_alert_rule_notifications_id'), 'alert_rule_notifications', ['id'], unique=False)
    op.create_table('incident_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alert_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correlation_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('incident_alerts_alert_id_fkey')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incident_alerts_incident_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_alerts_pkey'))
    )
    op.create_index(op.f('ix_incident_alerts_id'), 'incident_alerts', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fingerprint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('PROMETHEUS', 'ELK', 'CUSTOM', name='alertsourceenum'), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('alerts_organization_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('alerts_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey')),
    sa.UniqueConstraint('fingerprint', name=op.f('alerts_fingerprint_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('configuration', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('notification_channels_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_channels_pkey'))
    )
    op.create_index(op.f('ix_notification_channels_id'), 'notification_channels', ['id'], unique=False)
    op.create_table('team_invites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitestatusenum'), autoincrement=False, nullable=False),
    sa.Column('invited_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invite_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('team_invites_invited_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('team_invites_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('team_invites_pkey')),
    sa.UniqueConstraint('invite_token', name=op.f('team_invites_invite_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_team_invites_id'), 'team_invites', ['id'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change_type', postgresql.ENUM('DEPLOY', 'CONFIG', 'INFRA', name='changetypeenum'), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('change_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('change_events_organization_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('change_events_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('change_events_pkey'))
    )
    op.create_index(op.f('ix_change_events_id'), 'change_events', ['id'], unique=False)
    op.create_table('rca_timeline_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hypothesis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['root_cause_hypotheses.id'], name=op.f('rca_timeline_events_hypothesis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rca_timeline_events_pkey'))
    )
    op.create_index(op.f('ix_rca_timeline_events_id'), 'rca_timeline_events', ['id'], unique=False)
    op.create_table('service_metric_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('avg_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('p95_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('p99_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requests_per_second', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpu_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memory_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('service_metric_snapshots_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_metric_snapshots_pkey'))
    )
    op.create_index(op.f('ix_service_metric_snapshots_id'), 'service_metric_snapshots', ['id'], unique=False)
    op.create_table('root_cause_hypotheses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('root_cause_hypotheses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_type', postgresql.ENUM('SERVICE', 'CHANGE_EVENT', 'INFRA', name='entitytype'), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='root_cause_hypotheses_incident_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='root_cause_hypotheses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_root_cause_hypotheses_id'), 'root_cause_hypotheses', ['id'], unique=False)
    op.create_table('incident_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('impact_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incident_services_incident_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('incident_services_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_services_pkey'))
    )
    op.create_index(op.f('ix_incident_services_id'), 'incident_services', ['id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'PAUSED', name='alertrulestatusenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('alert_rules_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_rules_pkey'))
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('rca_evidence',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hypothesis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['root_cause_hypotheses.id'], name=op.f('rca_evidence_hypothesis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rca_evidence_pkey'))
    )
    op.create_index(op.f('ix_rca_evidence_id'), 'rca_evidence', ['id'], unique=False)
    op.create_table('incident_timeline',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('metric_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('annotation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incident_timeline_incident_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_timeline_pkey'))
    )
    op.create_index(op.f('ix_incident_timeline_id'), 'incident_timeline', ['id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('ROOT_CAUSE_ANALYSIS', 'ANOMALY_DETECTION', 'ALERT_CORRELATION', 'SEVERITY_PREDICTION', 'SERVICE_DEPENDENCY', name='aimodeltypeenum'), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'TRAINING', 'IDLE', 'ERROR', name='aimodelstatusenum'), autoincrement=False, nullable=False),
    sa.Column('training_samples', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('false_positive_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('false_negative_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_trained_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('ai_models_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_models_pkey'))
    )
    op.create_index(op.f('ix_ai_models_id'), 'ai_models', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('primary_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'MITIGATED', 'RESOLVED', name='statusenum'), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('affected_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('incidents_organization_id_fkey')),
    sa.ForeignKeyConstraint(['primary_service_id'], ['services.id'], name=op.f('incidents_primary_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_table('service_dependencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dependency_type', postgresql.ENUM('UPSTREAM', 'DOWNSTREAM', 'BIDIRECTIONAL', name='dependencytypeenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_service_id'], ['services.id'], name=op.f('service_dependencies_source_service_id_fkey')),
    sa.ForeignKeyConstraint(['target_service_id'], ['services.id'], name=op.f('service_dependencies_target_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_dependencies_pkey'))
    )
    op.create_index(op.f('ix_service_dependencies_id'), 'service_dependencies', ['id'], unique=False)
    op.create_table('suppression_policies',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('impact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_window', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'PAUSED', name='alertrulestatusenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('suppression_policies_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('suppression_policies_pkey'))
    )
    op.create_index(op.f('ix_suppression_policies_id'), 'suppression_policies', ['id'], unique=False)
    op.drop_index(op.f('ix_logs_trace_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_index('ix_logs_service_timestamp', table_name='logs')
    op.drop_index(op.f('ix_logs_service_name'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index('ix_events_type', table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index('ix_events_service_timestamp', table_name='events')
    op.drop_index(op.f('ix_events_service_name'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
