"""add service columns and new tables

Revision ID: 693389fe6076
Revises: 30d5d11f15b6
Create Date: 2026-01-07 12:01:36.753802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '693389fe6076'
down_revision = '30d5d11f15b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ROOT_CAUSE_ANALYSIS', 'ANOMALY_DETECTION', 'ALERT_CORRELATION', 'SEVERITY_PREDICTION', 'SERVICE_DEPENDENCY', name='aimodeltypeenum'), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'TRAINING', 'IDLE', 'ERROR', name='aimodelstatusenum'), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('false_negative_rate', sa.Float(), nullable=True),
    sa.Column('last_trained_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_id'), 'ai_models', ['id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PAUSED', name='alertrulestatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('mttr_minutes', sa.Float(), nullable=True),
    sa.Column('mttd_minutes', sa.Float(), nullable=True),
    sa.Column('noise_reduction_percentage', sa.Float(), nullable=True),
    sa.Column('error_budget_percentage', sa.Float(), nullable=True),
    sa.Column('raw_alerts_count', sa.Integer(), nullable=True),
    sa.Column('correlated_groups_count', sa.Integer(), nullable=True),
    sa.Column('incidents_count', sa.Integer(), nullable=True),
    sa.Column('p0_incidents', sa.Integer(), nullable=True),
    sa.Column('p1_incidents', sa.Integer(), nullable=True),
    sa.Column('p2_incidents', sa.Integer(), nullable=True),
    sa.Column('p3_incidents', sa.Integer(), nullable=True),
    sa.Column('p4_incidents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_id'), 'analytics_snapshots', ['id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PROMETHEUS', 'OPENTELEMETRY', 'DATADOG', 'GITHUB', 'SLACK', 'ELASTICSEARCH', 'PAGERDUTY', name='integrationtypeenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'SYNCED', 'ERROR', name='integrationstatusenum'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('configuration', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_id'), 'notification_channels', ['id'], unique=False)
    op.create_table('suppression_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('time_window', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PAUSED', name='alertrulestatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_policies_id'), 'suppression_policies', ['id'], unique=False)
    op.create_table('team_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitestatusenum'), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('invite_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_team_invites_id'), 'team_invites', ['id'], unique=False)
    op.create_table('alert_rule_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('notification_channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['notification_channel_id'], ['notification_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rule_notifications_id'), 'alert_rule_notifications', ['id'], unique=False)
    op.create_table('deployment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('deployed_by', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('repository', sa.String(), nullable=True),
    sa.Column('deployment_started_at', sa.DateTime(), nullable=False),
    sa.Column('deployment_completed_at', sa.DateTime(), nullable=True),
    sa.Column('rollback_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_events_id'), 'deployment_events', ['id'], unique=False)
    op.create_table('service_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_service_id', sa.Integer(), nullable=False),
    sa.Column('target_service_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.Enum('UPSTREAM', 'DOWNSTREAM', 'BIDIRECTIONAL', name='dependencytypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['source_service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['target_service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_dependencies_id'), 'service_dependencies', ['id'], unique=False)
    op.create_table('service_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_latency_ms', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('requests_per_second', sa.Float(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_metric_snapshots_id'), 'service_metric_snapshots', ['id'], unique=False)
    op.create_table('incident_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.Enum('ERROR', 'WARN', 'INFO', 'DEBUG', name='loglevelenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('log_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_logs_id'), 'incident_logs', ['id'], unique=False)
    op.create_table('incident_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('event_label', sa.String(), nullable=True),
    sa.Column('annotation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_id'), 'incident_timeline', ['id'], unique=False)
    op.create_table('rca_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['root_cause_hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_evidence_id'), 'rca_evidence', ['id'], unique=False)
    op.create_table('rca_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('highlighted_text', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['root_cause_hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_reasons_id'), 'rca_reasons', ['id'], unique=False)
    op.create_table('rca_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['root_cause_hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_timeline_events_id'), 'rca_timeline_events', ['id'], unique=False)
    op.drop_index('ix_model_training_labels_id', table_name='model_training_labels')
    op.drop_table('model_training_labels')
    op.drop_index('ix_causal_edges_id', table_name='causal_edges')
    op.drop_table('causal_edges')
    op.drop_index('ix_service_baselines_id', table_name='service_baselines')
    op.drop_table('service_baselines')
    op.drop_index('ix_incident_features_id', table_name='incident_features')
    op.drop_table('incident_features')
    op.drop_index('ix_overrides_id', table_name='overrides')
    op.drop_table('overrides')
    op.drop_index('ix_telemetry_sources_id', table_name='telemetry_sources')
    op.drop_table('telemetry_sources')
    op.drop_index('ix_ai_decisions_id', table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index('ix_cluster_members_id', table_name='cluster_members')
    op.drop_table('cluster_members')
    op.drop_index('ix_incident_clusters_cluster_signature', table_name='incident_clusters')
    op.drop_index('ix_incident_clusters_id', table_name='incident_clusters')
    op.drop_table('incident_clusters')
    op.add_column('incidents', sa.Column('affected_users', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('root_cause_hypotheses', sa.Column('title', sa.String(), nullable=False))
    op.add_column('root_cause_hypotheses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('root_cause_hypotheses', sa.Column('is_primary', sa.Integer(), nullable=False))
    # Create enum type for service health status
    op.execute("""
        CREATE TYPE servicehealthenum AS ENUM ('healthy', 'degraded', 'critical', 'unknown');
    """)
    op.add_column('services', sa.Column('health_status', sa.Enum('healthy', 'degraded', 'critical', 'unknown', name='servicehealthenum'), nullable=False, server_default='unknown'))
    op.add_column('services', sa.Column('avg_latency', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('error_rate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_active')
    op.drop_column('services', 'error_rate')
    op.drop_column('services', 'avg_latency')
    op.drop_column('services', 'health_status')
    # Drop enum type for service health status
    op.execute("""
        DROP TYPE IF EXISTS servicehealthenum;
    """)
    op.drop_column('root_cause_hypotheses', 'is_primary')
    op.drop_column('root_cause_hypotheses', 'description')
    op.drop_column('root_cause_hypotheses', 'title')
    op.drop_column('incidents', 'description')
    op.drop_column('incidents', 'ai_confidence')
    op.drop_column('incidents', 'affected_users')
    op.create_table('incident_clusters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('incident_clusters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cluster_signature', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='incident_clusters_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='incident_clusters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_incident_clusters_id', 'incident_clusters', ['id'], unique=False)
    op.create_index('ix_incident_clusters_cluster_signature', 'incident_clusters', ['cluster_signature'], unique=False)
    op.create_table('cluster_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['incident_clusters.id'], name='cluster_members_cluster_id_fkey'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='cluster_members_incident_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cluster_members_pkey')
    )
    op.create_index('ix_cluster_members_id', 'cluster_members', ['id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('decision_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('decision_output', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='ai_decisions_incident_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_decisions_pkey')
    )
    op.create_index('ix_ai_decisions_id', 'ai_decisions', ['id'], unique=False)
    op.create_table('telemetry_sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('METRICS', 'LOGS', 'TRACES', 'CHANGES', name='typeenum'), autoincrement=False, nullable=False),
    sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='telemetry_sources_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='telemetry_sources_pkey')
    )
    op.create_index('ix_telemetry_sources_id', 'telemetry_sources', ['id'], unique=False)
    op.create_table('overrides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('override_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='overrides_incident_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='overrides_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='overrides_pkey')
    )
    op.create_index('ix_overrides_id', 'overrides', ['id'], unique=False)
    op.create_table('incident_features',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_type', postgresql.ENUM('LATENCY_SPIKE', 'ERROR_RATE_CHANGE', 'CPU_ANOMALY', 'LOG_ENTROPY', name='featuretypeenum'), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('window_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='incident_features_incident_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='incident_features_pkey')
    )
    op.create_index('ix_incident_features_id', 'incident_features', ['id'], unique=False)
    op.create_table('service_baselines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_type', postgresql.ENUM('LATENCY_SPIKE', 'ERROR_RATE_CHANGE', 'CPU_ANOMALY', 'LOG_ENTROPY', name='featuretypeenum'), autoincrement=False, nullable=False),
    sa.Column('baseline_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stddev', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='service_baselines_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_baselines_pkey')
    )
    op.create_index('ix_service_baselines_id', 'service_baselines', ['id'], unique=False)
    op.create_table('causal_edges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='causal_edges_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='causal_edges_pkey')
    )
    op.create_index('ix_causal_edges_id', 'causal_edges', ['id'], unique=False)
    op.create_table('model_training_labels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('root_cause_entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('root_cause_entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='model_training_labels_incident_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='model_training_labels_pkey')
    )
    op.create_index('ix_model_training_labels_id', 'model_training_labels', ['id'], unique=False)
    op.drop_index(op.f('ix_rca_timeline_events_id'), table_name='rca_timeline_events')
    op.drop_table('rca_timeline_events')
    op.drop_index(op.f('ix_rca_reasons_id'), table_name='rca_reasons')
    op.drop_table('rca_reasons')
    op.drop_index(op.f('ix_rca_evidence_id'), table_name='rca_evidence')
    op.drop_table('rca_evidence')
    op.drop_index(op.f('ix_incident_timeline_id'), table_name='incident_timeline')
    op.drop_table('incident_timeline')
    op.drop_index(op.f('ix_incident_logs_id'), table_name='incident_logs')
    op.drop_table('incident_logs')
    op.drop_index(op.f('ix_service_metric_snapshots_id'), table_name='service_metric_snapshots')
    op.drop_table('service_metric_snapshots')
    op.drop_index(op.f('ix_service_dependencies_id'), table_name='service_dependencies')
    op.drop_table('service_dependencies')
    op.drop_index(op.f('ix_deployment_events_id'), table_name='deployment_events')
    op.drop_table('deployment_events')
    op.drop_index(op.f('ix_alert_rule_notifications_id'), table_name='alert_rule_notifications')
    op.drop_table('alert_rule_notifications')
    op.drop_index(op.f('ix_team_invites_id'), table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_index(op.f('ix_suppression_policies_id'), table_name='suppression_policies')
    op.drop_table('suppression_policies')
    op.drop_index(op.f('ix_notification_channels_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_analytics_snapshots_id'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_ai_models_id'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
